In [1]:
import pandas as pd
import numpy  as np

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
df = pd.read_csv('TA_day.csv', parse_dates=['Date'])

In [13]:
# df[['Close', sma, 'cross_SMA_5', 'dif_SMA_5', 'dif']].iloc[:-500000,:].to_excel('dfdf.xlsx')
# df[['Close', sma, 'cross_SMA_5', 'dif_SMA_5', 'dif']].iloc[200:300,:]
df

Unnamed: 0       Date    Open    High     Low   Close        Volume  \
0                0 2006-01-23  239.50  239.50  218.49  218.89  1.130995e+09   
1                1 2006-01-24  221.00  224.68  219.66  224.00  1.991942e+09   
2                2 2006-01-25  225.50  231.00  225.00  228.38  3.534137e+09   
3                3 2006-01-26  228.20  229.41  223.51  224.47  1.721376e+09   
4                4 2006-01-27  225.75  231.50  224.00  228.75  2.901323e+09   
...            ...        ...     ...     ...     ...     ...           ...   
122158      122158 2019-05-23  651.20  653.00  650.40  652.80  3.124316e+06   
122159      122159 2019-05-24  650.60  654.40  650.60  654.40  5.298356e+06   
122160      122160 2019-05-27  650.60  653.80  650.40  653.20  9.374714e+06   
122161      122161 2019-05-28  653.40  653.40  651.20  652.80  7.370344e+06   
122162      122162 2019-05-29  650.80  653.20  650.60  650.60  5.456527e+07   

       Symbol     ADX_25     ADX_36  ...  HT_SINE_sine  HT_SINE_leadsine  \
0        GAZP        NaN        NaN  ...           NaN               NaN   
1        GAZP        NaN        NaN  ...           NaN               NaN   
2        GAZP        NaN        NaN  ...           NaN               NaN   
3        GAZP        NaN        NaN  ...           NaN               NaN   
4        GAZP        NaN        NaN  ...           NaN               NaN   
...       ...        ...        ...  ...           ...               ...   
122158   MFON  23.214150  18.487554  ...     -0.712080         -0.999975   
122159   MFON  23.959622  18.729043  ...     -0.665884         -0.998392   
122160   MFON  24.684299  18.969202  ...     -0.640195         -0.995894   
122161   MFON  25.379988  19.202689  ...     -0.656501         -0.997605   
122162   MFON  26.076742  19.446569  ...     -0.701346         -0.999967   

        BBANDS_upperband  BBANDS_middleband  BBANDS_lowerband   MAMA_mama  \
0                    NaN                NaN               NaN         NaN   
1                    NaN                NaN               NaN         NaN   
2                    NaN                NaN               NaN         NaN   
3                    NaN                NaN               NaN         NaN   
4             232.056094            224.898        217.739906         NaN   
...                  ...                ...               ...         ...   
122158        652.800000            652.640        652.480000  652.578028   
122159        654.408545            653.000        651.591455  652.906559   
122160        654.472923            653.120        651.767077  652.935060   
122161        654.459846            653.160        651.860154  652.867530   
122162        655.217967            652.760        650.302033  652.754154   

         MAMA_fama  dif_25  dif_SMA_25  cross_SMA_25  
0              NaN       1         NaN             1  
1              NaN       1         NaN             1  
2              NaN       1         NaN             1  
3              NaN       1         NaN             1  
4              NaN       1         NaN             1  
...            ...     ...         ...           ...  
122158  651.066056       1      -1.096             0  
122159  651.231993       1      -2.440             0  
122160  651.314700       1      -1.120             0  
122161  651.702908       1      -0.624             0  
122162  651.729189      -1       1.592            -1  

[122163 rows x 125 columns]

In [42]:
list(df)

['Unnamed: 0',
 'Date',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Symbol',
 'ADX_25',
 'ADX_36',
 'ADXR_25',
 'ADXR_36',
 'APO_25',
 'APO_36',
 'AROONOSC_25',
 'AROONOSC_36',
 'BOP_25',
 'BOP_36',
 'CCI_25',
 'CCI_36',
 'CMO_25',
 'CMO_36',
 'DX_25',
 'DX_36',
 'MFI_25',
 'MFI_36',
 'MINUS_DI_25',
 'MINUS_DI_36',
 'MINUS_DM_25',
 'MINUS_DM_36',
 'MOM_25',
 'MOM_36',
 'PLUS_DI_25',
 'PLUS_DI_36',
 'PLUS_DM_25',
 'PLUS_DM_36',
 'PPO_25',
 'PPO_36',
 'ROC_25',
 'ROC_36',
 'ROCP_25',
 'ROCP_36',
 'ROCR_25',
 'ROCR_36',
 'ROCR100_25',
 'ROCR100_36',
 'RSI_25',
 'RSI_36',
 'TRIX_25',
 'TRIX_36',
 'ULTOSC_25',
 'ULTOSC_36',
 'WILLR_25',
 'WILLR_36',
 'HT_DCPERIOD_25',
 'HT_DCPERIOD_36',
 'HT_DCPHASE_25',
 'HT_DCPHASE_36',
 'HT_TRENDMODE_25',
 'HT_TRENDMODE_36',
 'DEMA_25',
 'DEMA_36',
 'EMA_25',
 'EMA_36',
 'HT_TRENDLINE_25',
 'HT_TRENDLINE_36',
 'KAMA_25',
 'KAMA_36',
 'MA_25',
 'MA_36',
 'MIDPOINT_25',
 'MIDPOINT_36',
 'MIDPRICE_25',
 'MIDPRICE_36',
 'SMA_25',
 'SMA_36',
 'T3_25',
 '

In [52]:
# import talib
# from talib import abstract
# from sklearn.preprocessing import MinMaxScaler
# import mplfinance as mpf
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# #import labeling.ipynb
# from tqdm import tqdm_notebook as tqdm
# display(len(talib.get_functions()))
# display((talib.get_functions()))
# display(talib.get_function_groups())
# upperband, middleband, lowerband = BBANDS(mer['Close'], timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
# upperband

In [53]:
labels = ['con_div_MACD', 'cross_SMA_25', 'BB']
for i in labels:
    display(i)
    display(np.unique(np.array(mer[i]), return_counts=True))

'con_div_MACD'

(array([-1,  0,  1], dtype=int64), array([15160, 84441, 14792], dtype=int64))

'cross_SMA_25'

(array([-1,  0,  1], dtype=int64),
 array([  5743, 102896,   5754], dtype=int64))

'BB'

(array([-1,  0,  1]), array([10300, 93246, 10847], dtype=int64))

In [32]:
#make labels

#make MACD
df['max_close']    = np.where(df['Close']         > df['Close'].shift(1), 1, -1)
df['max_MACD']     = np.where(df['MACD_macdhist'] > df['MACD_macdhist'].shift(1), 1, -1)
df['con_div_MACD'] = np.where(df['max_close'] == -1,  
                              np.where(df['max_MACD'] ==  1,  1, 0), 
                              np.where(df['max_MACD'] == -1, -1, 0)
                             )
df[['Date', "Symbol", 'MACD_macd', 'MACD_macdsignal', 'MACD_macdhist', 'Close', 'max_close', 'max_MACD', 'con_div_MACD']] 

#make sma
sma = 'SMA_25'
df['dif_25'] = np.where(df[sma] > df['Close'], -1, 1)
df['dif_SMA_25']   = df[sma] - df['Close']
df['cross_SMA_25'] = np.where(
    df['dif_SMA_25'] * df['dif_SMA_25'].shift(1)>0, 
    0, 
    np.where(df[sma]>df['Close'], -1, 1))

#make RSI
rsi = 'RSI_25'
df['rsi_max'] = np.where(df['RSI_25']>df['RSI_25'].shift(1), 1, -1)

df['RSI_25_div'] = np. where(df['rsi_max']*df['max_close'] > 0, 0, np.where(df['rsi_max']>0, 1, -1) )
df[['RSI_25_div', 'rsi_max', 'Close', 'RSI_25', 'max_close']]


#make BB
df['BB_up_Close'] = df['Close'] - df['BBANDS_upperband'].shift(1)
df['BB_do_Close'] = df['Close'] - df['BBANDS_lowerband'].shift(1)
df['BB_mi_Close'] = df['Close'] - df['BBANDS_middleband'].shift(1)

df['cross_BB_up'] = np.where(df['BB_up_Close']>0, 
                              np.where(df['BB_up_Close'].shift(1)<0,1,0),0
                             )

df['cross_BB_do'] = np.where(df['BB_do_Close']<0, 
                              np.where(df['BB_do_Close'].shift(1)>0,-1,0),0
                             )

df['cross_MI_do'] = np.where(df['BB_mi_Close']*df['BB_mi_Close'].shift(1), 0, 10)
df['BB'] = df['cross_BB_up'] + df['cross_BB_do']# + mer['cross_MI_do']

Date Symbol  MACD_macd  MACD_macdsignal  MACD_macdhist   Close  \
0      2006-01-23   GAZP        NaN              NaN            NaN  218.89   
1      2006-01-24   GAZP        NaN              NaN            NaN  224.00   
2      2006-01-25   GAZP        NaN              NaN            NaN  228.38   
3      2006-01-26   GAZP        NaN              NaN            NaN  224.47   
4      2006-01-27   GAZP        NaN              NaN            NaN  228.75   
...           ...    ...        ...              ...            ...     ...   
122158 2019-05-23   MFON   1.700179         2.062271      -0.362092  652.80   
122159 2019-05-24   MFON   1.737581         1.997333      -0.259753  654.40   
122160 2019-05-27   MFON   1.651355         1.928138      -0.276782  653.20   
122161 2019-05-28   MFON   1.533072         1.849125      -0.316052  652.80   
122162 2019-05-29   MFON   1.247431         1.728786      -0.481355  650.60   

        max_close  max_MACD  con_div_MACD  
0              -1        -1             0  
1               1        -1            -1  
2               1        -1            -1  
3              -1        -1             0  
4               1        -1            -1  
...           ...       ...           ...  
122158          1         1             0  
122159          1         1             0  
122160         -1        -1             0  
122161         -1        -1             0  
122162         -1        -1             0  

[122163 rows x 9 columns]

In [9]:
%%time
n = 50
t = 55

last_n_bar_all = pd.DataFrame()

for ii in df['Symbol'].unique():
    test = df[df['Symbol'] == ii][['Date', 'Symbol', 'Close']]
    test = np.array(test)
    
    all_15 = np.zeros(0)
    for i in range(t, len(test)):
        df_15 = test[i-n+1:i+1]
        all_15 = np.append(all_15, df_15)
    #    display(i)
    display(all_15.shape)        
    display(len(all_15)/n)   
    zz = np.reshape(all_15, (int(len(all_15)/3), 3))
    ss = np.reshape(zz[:,-1], (int(len(zz)/n), n))
    last_n_bar = pd.DataFrame(np.concatenate([test[t:,:], ss], axis=1))
    last_n_bar.columns = [ 'Date', 'Symbol', 'Close'] + list(range(n))
    last_n_bar_all = last_n_bar_all.append(last_n_bar)
last_n_bar_all

(543600,)

10872.0

(508350,)

10167.0

(633600,)

12672.0

(525300,)

10506.0

(487800,)

9756.0

(481800,)

9636.0

(325350,)

6507.0

(471750,)

9435.0

(230550,)

4611.0

(515100,)

10302.0

(615450,)

12309.0

(396900,)

7938.0

(522150,)

10443.0

(543900,)

10878.0

(434100,)

8682.0

(614400,)

12288.0

(279300,)

5586.0

(534600,)

10692.0

(532350,)

10647.0

(246000,)

4920.0

(627600,)

12552.0

(627600,)

12552.0

(487800,)

9756.0

(565200,)

11304.0

(696600,)

13932.0

(470100,)

9402.0

(456000,)

9120.0

(450900,)

9018.0

(199350,)

3987.0

(522000,)

10440.0

(490500,)

9810.0

(512250,)

10245.0

(635700,)

12714.0

(635700,)

12714.0

(325050,)

6501.0

(637950,)

12759.0

(236550,)

4731.0

Wall time: 5min 42s


Date Symbol   Close       0       1       2       3       4  \
0    2006-04-12   GAZP   264.7  219.02  223.99   221.5  221.01  220.45   
1    2006-04-13   GAZP  263.49  223.99   221.5  221.01  220.45   220.5   
2    2006-04-14   GAZP   267.9   221.5  221.01  220.45   220.5     221   
3    2006-04-17   GAZP  269.45  221.01  220.45   220.5     221     222   
4    2006-04-18   GAZP  271.69  220.45   220.5     221     222     222   
...         ...    ...     ...     ...     ...     ...     ...     ...   
1572 2019-05-23   MFON   652.8   632.2   634.2   635.2   634.4   633.2   
1573 2019-05-24   MFON   654.4   634.2   635.2   634.4   633.2   636.2   
1574 2019-05-27   MFON   653.2   635.2   634.4   633.2   636.2   634.2   
1575 2019-05-28   MFON   652.8   634.4   633.2   636.2   634.2   639.4   
1576 2019-05-29   MFON   650.6   633.2   636.2   634.2   639.4   639.6   

           5       6  ...      40      41      42      43      44      45  \
0      220.5     221  ...   230.4  230.15   230.5  231.52   238.5   243.3   
1        221     222  ...  230.15   230.5  231.52   238.5   243.3  250.29   
2        222     222  ...   230.5  231.52   238.5   243.3  250.29   268.7   
3        222  219.95  ...  231.52   238.5   243.3  250.29   268.7   262.5   
4     219.95  219.89  ...   238.5   243.3  250.29   268.7   262.5   264.7   
...      ...     ...  ...     ...     ...     ...     ...     ...     ...   
1572   636.2   634.2  ...   652.6   652.6   652.6   652.6   652.6   652.6   
1573   634.2   639.4  ...   652.6   652.6   652.6   652.6   652.6   652.6   
1574   639.4   639.6  ...   652.6   652.6   652.6   652.6   652.6   652.6   
1575   639.6   640.4  ...   652.6   652.6   652.6   652.6   652.6   652.6   
1576   640.4   639.8  ...   652.6   652.6   652.6   652.6   652.6   652.8   

          46      47      48      49  
0     250.29   268.7   262.5   264.7  
1      268.7   262.5   264.7  263.49  
2      262.5   264.7  263.49   267.9  
3      264.7  263.49   267.9  269.45  
4     263.49   267.9  269.45  271.69  
...      ...     ...     ...     ...  
1572   652.6   652.6   652.6   652.8  
1573   652.6   652.6   652.8   654.4  
1574   652.6   652.8   654.4   653.2  
1575   652.8   654.4   653.2   652.8  
1576   654.4   653.2   652.8   650.6  

[120128 rows x 53 columns]

In [43]:
mer = pd.merge(last_n_bar_all, df, on = ['Date', 'Symbol', 'Close'], how = 'inner')
display(df.shape, last_n_bar_all.shape, mer.shape)
mer.dropna(inplace=True)
display(mer.shape)
mer

(122163, 128)

(120128, 53)

(120128, 178)

(114393, 178)

Date Symbol   Close       0       1       2       3       4  \
155    2006-11-21   GAZP   291.4   289.9  293.99  292.18  291.75  293.82   
156    2006-11-22   GAZP  288.01  293.99  292.18  291.75  293.82  294.75   
157    2006-11-23   GAZP   289.7  292.18  291.75  293.82  294.75  288.01   
158    2006-11-24   GAZP  289.99  291.75  293.82  294.75  288.01   280.8   
159    2006-11-27   GAZP  288.75  293.82  294.75  288.01   280.8     272   
...           ...    ...     ...     ...     ...     ...     ...     ...   
120123 2019-05-23   MFON   652.8   632.2   634.2   635.2   634.4   633.2   
120124 2019-05-24   MFON   654.4   634.2   635.2   634.4   633.2   636.2   
120125 2019-05-27   MFON   653.2   635.2   634.4   633.2   636.2   634.2   
120126 2019-05-28   MFON   652.8   634.4   633.2   636.2   634.2   639.4   
120127 2019-05-29   MFON   650.6   633.2   636.2   634.2   639.4   639.6   

             5       6  ... BBANDS_middleband BBANDS_lowerband   MAMA_mama  \
155     294.75  288.01  ...           290.552       284.093326  290.600826   
156     288.01   280.8  ...           289.354       283.729758  290.471285   
157      280.8     272  ...           288.566       284.751782  290.432721   
158        272   262.1  ...           288.958       285.043158  290.211360   
159      262.1  273.91  ...           289.570       287.263800  290.138292   
...        ...     ...  ...               ...              ...         ...   
120123   636.2   634.2  ...           652.640       652.480000  652.578028   
120124   634.2   639.4  ...           653.000       651.591455  652.906559   
120125   639.4   639.6  ...           653.120       651.767077  652.935060   
120126   639.6   640.4  ...           653.160       651.860154  652.867530   
120127   640.4   639.8  ...           652.760       650.302033  652.754154   

         MAMA_fama dif_25 dif_SMA_25 cross_SMA_25 max_close max_MACD  \
155     290.386593     -1     0.0224            0         1        1   
156     290.388710     -1     3.1728            0        -1       -1   
157     290.389811     -1     1.0832            0         1        1   
158     290.345198     -1     0.3888            0         1        1   
159     290.340025     -1     1.2908            0        -1       -1   
...            ...    ...        ...          ...       ...      ...   
120123  651.066056      1    -1.0960            0         1        1   
120124  651.231993      1    -2.4400            0         1        1   
120125  651.314700      1    -1.1200            0        -1       -1   
120126  651.702908      1    -0.6240            0        -1       -1   
120127  651.729189     -1     1.5920           -1        -1       -1   

       con_div_MACD  
155               0  
156               0  
157               0  
158               0  
159               0  
...             ...  
120123            0  
120124            0  
120125            0  
120126            0  
120127            0  

[114393 rows x 178 columns]

In [54]:
mer.to_csv('mer.csv')

In [6]:
mer = pd.read_csv('mer.csv', parse_dates=['Date'])

In [8]:
mer = mer.drop(columns = 'Unnamed: 0')
mer

Date Symbol   Close       0       1       2       3       4  \
0      2006-11-21   GAZP  291.40  289.90  293.99  292.18  291.75  293.82   
1      2006-11-22   GAZP  288.01  293.99  292.18  291.75  293.82  294.75   
2      2006-11-23   GAZP  289.70  292.18  291.75  293.82  294.75  288.01   
3      2006-11-24   GAZP  289.99  291.75  293.82  294.75  288.01  280.80   
4      2006-11-27   GAZP  288.75  293.82  294.75  288.01  280.80  272.00   
...           ...    ...     ...     ...     ...     ...     ...     ...   
114388 2019-05-23   MFON  652.80  632.20  634.20  635.20  634.40  633.20   
114389 2019-05-24   MFON  654.40  634.20  635.20  634.40  633.20  636.20   
114390 2019-05-27   MFON  653.20  635.20  634.40  633.20  636.20  634.20   
114391 2019-05-28   MFON  652.80  634.40  633.20  636.20  634.20  639.40   
114392 2019-05-29   MFON  650.60  633.20  636.20  634.20  639.40  639.60   

             5       6  ...  BBANDS_middleband  BBANDS_lowerband   MAMA_mama  \
0       294.75  288.01  ...            290.552        284.093326  290.600826   
1       288.01  280.80  ...            289.354        283.729758  290.471285   
2       280.80  272.00  ...            288.566        284.751782  290.432721   
3       272.00  262.10  ...            288.958        285.043158  290.211360   
4       262.10  273.91  ...            289.570        287.263800  290.138292   
...        ...     ...  ...                ...               ...         ...   
114388  636.20  634.20  ...            652.640        652.480000  652.578028   
114389  634.20  639.40  ...            653.000        651.591455  652.906559   
114390  639.40  639.60  ...            653.120        651.767077  652.935060   
114391  639.60  640.40  ...            653.160        651.860154  652.867530   
114392  640.40  639.80  ...            652.760        650.302033  652.754154   

         MAMA_fama  dif_25  dif_SMA_25  cross_SMA_25  max_close  max_MACD  \
0       290.386593      -1      0.0224             0          1         1   
1       290.388710      -1      3.1728             0         -1        -1   
2       290.389811      -1      1.0832             0          1         1   
3       290.345198      -1      0.3888             0          1         1   
4       290.340025      -1      1.2908             0         -1        -1   
...            ...     ...         ...           ...        ...       ...   
114388  651.066056       1     -1.0960             0          1         1   
114389  651.231993       1     -2.4400             0          1         1   
114390  651.314700       1     -1.1200             0         -1        -1   
114391  651.702908       1     -0.6240             0         -1        -1   
114392  651.729189      -1      1.5920            -1         -1        -1   

        con_div_MACD  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
114388             0  
114389             0  
114390             0  
114391             0  
114392             0  

[114393 rows x 178 columns]

In [ ]:
d
